[all]
localhost ansible_connection=local 

[all:vars]
site=site1
aap_hostname = aapc1.hampden.com
aap_username = "{{ lookup('env', 'AAP_USERNAME') }}"
aap_password = "{{ lookup('env', 'AAP_PASSWORD') }}"
aap_validate_certs = "{{ lookup('env', 'AAP_VALIDATE_CERTS') }}"
aap_hub_url= 'https://{{ aap_hostname }}/api/galaxy/'
aap_hub_token= "{{ lookup('env', 'AAP_SYSTEM_SITE1_HUB_TOKEN') }}"

# gateway_authenticators.yml
ldap_bind_password = "{{ lookup('env', 'LDAP_BIND_PASSWORD') }}"